/**
 * Seed Recipe Database
 * A curated collection of recipes for Remy's core functionality
 * Each recipe includes exact ingredients with quantities for accurate pantry matching
 */

export interface SeedRecipe {
  title: string;
  description: string;
  cuisine: string;
  difficulty: 'easy' | 'medium' | 'hard';
  prepTime: number; // minutes
  cookingTime: number; // minutes
  servings: number;
  imageUrl: string;
  ingredients: Array<{
    name: string;
    amount: number;
    unit: string;
  }>;
  instructions: Array<{
    step: number;
    description: string;
  }>;
}

export const seedRecipes: SeedRecipe[] = [
  // ========== EASY RECIPES (15-30 min) ==========
  {
    title: 'Classic Spaghetti Aglio e Olio',
    description: 'Simple Italian pasta with garlic, olive oil, and red pepper flakes. A quick and delicious meal that uses pantry staples.',
    cuisine: 'Italian',
    difficulty: 'easy',
    prepTime: 5,
    cookingTime: 15,
    servings: 4,
    imageUrl: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=800',
    ingredients: [
      { name: 'spaghetti', amount: 400, unit: 'g' },
      { name: 'garlic', amount: 6, unit: 'cloves' },
      { name: 'olive oil', amount: 80, unit: 'ml' },
      { name: 'red pepper flakes', amount: 1, unit: 'tsp' },
      { name: 'parsley', amount: 30, unit: 'g' },
      { name: 'salt', amount: 1, unit: 'tsp' },
      { name: 'black pepper', amount: 0.5, unit: 'tsp' },
    ],
    instructions: [
      { step: 1, description: 'Cook spaghetti in salted boiling water according to package directions until al dente.' },
      { step: 2, description: 'While pasta cooks, thinly slice garlic cloves.' },
      { step: 3, description: 'Heat olive oil in a large pan over medium heat. Add garlic and red pepper flakes, cook for 2-3 minutes until fragrant (don\'t brown).' },
      { step: 4, description: 'Reserve 1 cup of pasta water, then drain pasta.' },
      { step: 5, description: 'Add pasta to the garlic oil, toss well. Add pasta water as needed to create a light sauce.' },
      { step: 6, description: 'Season with salt and pepper, garnish with fresh parsley. Serve immediately.' },
    ],
  },
  {
    title: 'Quick Chicken Stir-Fry',
    description: 'Colorful Asian-inspired stir-fry with tender chicken and crisp vegetables in a savory sauce.',
    cuisine: 'Asian',
    difficulty: 'easy',
    prepTime: 10,
    cookingTime: 15,
    servings: 4,
    imageUrl: 'https://images.unsplash.com/photo-1603073421155-d0c16c0e6e36?w=800',
    ingredients: [
      { name: 'chicken breast', amount: 500, unit: 'g' },
      { name: 'bell pepper', amount: 2, unit: 'pieces' },
      { name: 'broccoli', amount: 200, unit: 'g' },
      { name: 'carrot', amount: 2, unit: 'pieces' },
      { name: 'soy sauce', amount: 60, unit: 'ml' },
      { name: 'ginger', amount: 1, unit: 'tbsp' },
      { name: 'garlic', amount: 3, unit: 'cloves' },
      { name: 'vegetable oil', amount: 2, unit: 'tbsp' },
      { name: 'cornstarch', amount: 1, unit: 'tbsp' },
      { name: 'sesame oil', amount: 1, unit: 'tsp' },
    ],
    instructions: [
      { step: 1, description: 'Cut chicken into bite-sized pieces and toss with cornstarch.' },
      { step: 2, description: 'Cut bell peppers into strips, broccoli into florets, and slice carrots.' },
      { step: 3, description: 'Heat oil in a wok or large pan over high heat. Cook chicken until golden, about 5 minutes. Remove and set aside.' },
      { step: 4, description: 'Add vegetables to the pan, stir-fry for 3-4 minutes until crisp-tender.' },
      { step: 5, description: 'Return chicken to pan, add soy sauce, ginger, and garlic. Stir-fry for 2 minutes.' },
      { step: 6, description: 'Drizzle with sesame oil, toss well, and serve hot with rice.' },
    ],
  },
  {
    title: 'Caprese Salad',
    description: 'Fresh mozzarella, ripe tomatoes, and basil drizzled with balsamic glaze - a taste of summer.',
    cuisine: 'Italian',
    difficulty: 'easy',
    prepTime: 10,
    cookingTime: 0,
    servings: 4,
    imageUrl: 'https://images.unsplash.com/photo-1608897013039-887f21d8c804?w=800',
    ingredients: [
      { name: 'tomato', amount: 4, unit: 'pieces' },
      { name: 'mozzarella', amount: 400, unit: 'g' },
      { name: 'basil', amount: 20, unit: 'g' },
      { name: 'olive oil', amount: 60, unit: 'ml' },
      { name: 'balsamic vinegar', amount: 30, unit: 'ml' },
      { name: 'salt', amount: 1, unit: 'tsp' },
      { name: 'black pepper', amount: 0.5, unit: 'tsp' },
    ],
    instructions: [
      { step: 1, description: 'Slice tomatoes and mozzarella into 1/4-inch thick rounds.' },
      { step: 2, description: 'Arrange alternating slices of tomato and mozzarella on a platter.' },
      { step: 3, description: 'Tuck fresh basil leaves between the slices.' },
      { step: 4, description: 'Drizzle with olive oil and balsamic vinegar.' },
      { step: 5, description: 'Season with salt and freshly ground black pepper. Serve immediately.' },
    ],
  },
  {
    title: 'Simple Chicken Tacos',
    description: 'Seasoned chicken with fresh toppings in warm tortillas - perfect for Taco Tuesday!',
    cuisine: 'Mexican',
    difficulty: 'easy',
    prepTime: 10,
    cookingTime: 20,
    servings: 4,
    imageUrl: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=800',
    ingredients: [
      { name: 'chicken breast', amount: 600, unit: 'g' },
      { name: 'tortillas', amount: 8, unit: 'pieces' },
      { name: 'tomato', amount: 2, unit: 'pieces' },
      { name: 'lettuce', amount: 200, unit: 'g' },
      { name: 'cheddar cheese', amount: 150, unit: 'g' },
      { name: 'sour cream', amount: 120, unit: 'ml' },
      { name: 'cumin', amount: 1, unit: 'tbsp' },
      { name: 'paprika', amount: 1, unit: 'tsp' },
      { name: 'garlic powder', amount: 1, unit: 'tsp' },
      { name: 'lime', amount: 2, unit: 'pieces' },
    ],
    instructions: [
      { step: 1, description: 'Season chicken with cumin, paprika, and garlic powder.' },
      { step: 2, description: 'Cook chicken in a pan over medium heat for 6-7 minutes per side until cooked through.' },
      { step: 3, description: 'Let chicken rest for 5 minutes, then slice into strips.' },
      { step: 4, description: 'Warm tortillas in a dry pan or microwave.' },
      { step: 5, description: 'Dice tomatoes, shred lettuce, and grate cheese.' },
      { step: 6, description: 'Assemble tacos with chicken, vegetables, cheese, sour cream, and a squeeze of lime.' },
    ],
  },

  // ========== MEDIUM RECIPES (30-45 min) ==========
  {
    title: 'Homemade Chicken Curry',
    description: 'Aromatic Indian curry with tender chicken in a rich, spiced tomato-cream sauce.',
    cuisine: 'Indian',
    difficulty: 'medium',
    prepTime: 15,
    cookingTime: 35,
    servings: 6,
    imageUrl: 'https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?w=800',
    ingredients: [
      { name: 'chicken thigh', amount: 800, unit: 'g' },
      { name: 'onion', amount: 2, unit: 'pieces' },
      { name: 'tomato', amount: 4, unit: 'pieces' },
      { name: 'garlic', amount: 6, unit: 'cloves' },
      { name: 'ginger', amount: 2, unit: 'tbsp' },
      { name: 'heavy cream', amount: 200, unit: 'ml' },
      { name: 'curry powder', amount: 2, unit: 'tbsp' },
      { name: 'cumin', amount: 1, unit: 'tsp' },
      { name: 'turmeric', amount: 1, unit: 'tsp' },
      { name: 'vegetable oil', amount: 3, unit: 'tbsp' },
      { name: 'cilantro', amount: 30, unit: 'g' },
    ],
    instructions: [
      { step: 1, description: 'Cut chicken into bite-sized pieces and season with salt.' },
      { step: 2, description: 'Finely chop onions, garlic, and ginger. Dice tomatoes.' },
      { step: 3, description: 'Heat oil in a large pot over medium heat. Cook onions for 5 minutes until soft.' },
      { step: 4, description: 'Add garlic and ginger, cook for 1 minute. Add curry powder, cumin, and turmeric, toast for 30 seconds.' },
      { step: 5, description: 'Add chicken pieces, cook until browned on all sides.' },
      { step: 6, description: 'Add tomatoes and 1 cup water. Bring to boil, then simmer for 20 minutes.' },
      { step: 7, description: 'Stir in heavy cream, simmer for 5 more minutes. Garnish with fresh cilantro.' },
    ],
  },
  {
    title: 'Beef Bolognese Pasta',
    description: 'Rich Italian meat sauce simmered to perfection, served over fresh pasta.',
    cuisine: 'Italian',
    difficulty: 'medium',
    prepTime: 15,
    cookingTime: 45,
    servings: 6,
    imageUrl: 'https://images.unsplash.com/photo-1598866594230-a7c12756260f?w=800',
    ingredients: [
      { name: 'ground beef', amount: 500, unit: 'g' },
      { name: 'spaghetti', amount: 500, unit: 'g' },
      { name: 'onion', amount: 1, unit: 'piece' },
      { name: 'carrot', amount: 2, unit: 'pieces' },
      { name: 'celery', amount: 2, unit: 'stalks' },
      { name: 'garlic', amount: 4, unit: 'cloves' },
      { name: 'tomato paste', amount: 3, unit: 'tbsp' },
      { name: 'crushed tomatoes', amount: 800, unit: 'g' },
      { name: 'red wine', amount: 120, unit: 'ml' },
      { name: 'milk', amount: 60, unit: 'ml' },
      { name: 'parmesan cheese', amount: 100, unit: 'g' },
      { name: 'oregano', amount: 1, unit: 'tsp' },
    ],
    instructions: [
      { step: 1, description: 'Finely chop onion, carrot, celery, and garlic.' },
      { step: 2, description: 'Heat oil in a large pot, cook vegetables for 10 minutes until soft.' },
      { step: 3, description: 'Add ground beef, cook until browned, breaking it up with a spoon.' },
      { step: 4, description: 'Add tomato paste, cook for 2 minutes. Pour in red wine, let it reduce for 3 minutes.' },
      { step: 5, description: 'Add crushed tomatoes, oregano, salt, and pepper. Simmer for 30 minutes, stirring occasionally.' },
      { step: 6, description: 'Stir in milk in the last 5 minutes of cooking.' },
      { step: 7, description: 'Cook pasta according to package directions. Serve Bolognese over pasta with grated parmesan.' },
    ],
  },
  {
    title: 'Vegetable Pad Thai',
    description: 'Thai street food classic with rice noodles, crunchy vegetables, and tangy tamarind sauce.',
    cuisine: 'Thai',
    difficulty: 'medium',
    prepTime: 20,
    cookingTime: 15,
    servings: 4,
    imageUrl: 'https://images.unsplash.com/photo-1559314809-0d155014e29e?w=800',
    ingredients: [
      { name: 'rice noodles', amount: 300, unit: 'g' },
      { name: 'tofu', amount: 200, unit: 'g' },
      { name: 'egg', amount: 3, unit: 'pieces' },
      { name: 'bean sprouts', amount: 150, unit: 'g' },
      { name: 'carrot', amount: 1, unit: 'piece' },
      { name: 'scallion', amount: 4, unit: 'pieces' },
      { name: 'garlic', amount: 3, unit: 'cloves' },
      { name: 'peanuts', amount: 80, unit: 'g' },
      { name: 'tamarind paste', amount: 2, unit: 'tbsp' },
      { name: 'fish sauce', amount: 3, unit: 'tbsp' },
      { name: 'brown sugar', amount: 2, unit: 'tbsp' },
      { name: 'lime', amount: 2, unit: 'pieces' },
    ],
    instructions: [
      { step: 1, description: 'Soak rice noodles in warm water for 20 minutes until soft.' },
      { step: 2, description: 'Mix tamarind paste, fish sauce, and brown sugar for the sauce.' },
      { step: 3, description: 'Cut tofu into cubes. Julienne carrots. Chop scallions and crush peanuts.' },
      { step: 4, description: 'Heat oil in a wok, cook tofu until golden. Push to the side.' },
      { step: 5, description: 'Add eggs, scramble quickly, then mix with tofu.' },
      { step: 6, description: 'Add drained noodles, garlic, and carrots. Stir-fry for 2 minutes.' },
      { step: 7, description: 'Pour in sauce, toss well. Add bean sprouts and scallions. Serve with peanuts and lime wedges.' },
    ],
  },
  {
    title: 'Lemon Herb Roasted Chicken',
    description: 'Juicy roasted chicken with crispy skin, infused with lemon and fresh herbs.',
    cuisine: 'American',
    difficulty: 'medium',
    prepTime: 15,
    cookingTime: 60,
    servings: 4,
    imageUrl: 'https://images.unsplash.com/photo-1598103442097-8b74394b95c6?w=800',
    ingredients: [
      { name: 'whole chicken', amount: 1500, unit: 'g' },
      { name: 'lemon', amount: 2, unit: 'pieces' },
      { name: 'garlic', amount: 8, unit: 'cloves' },
      { name: 'rosemary', amount: 4, unit: 'sprigs' },
      { name: 'thyme', amount: 6, unit: 'sprigs' },
      { name: 'butter', amount: 50, unit: 'g' },
      { name: 'olive oil', amount: 3, unit: 'tbsp' },
      { name: 'potato', amount: 600, unit: 'g' },
      { name: 'salt', amount: 2, unit: 'tsp' },
      { name: 'black pepper', amount: 1, unit: 'tsp' },
    ],
    instructions: [
      { step: 1, description: 'Preheat oven to 200°C (400°F).' },
      { step: 2, description: 'Pat chicken dry, season inside and out with salt and pepper.' },
      { step: 3, description: 'Stuff cavity with lemon halves, garlic cloves, and herb sprigs.' },
      { step: 4, description: 'Rub butter and olive oil all over the skin.' },
      { step: 5, description: 'Cut potatoes into chunks, toss with oil, salt, and pepper. Arrange around chicken.' },
      { step: 6, description: 'Roast for 1 hour or until internal temperature reaches 75°C (165°F).' },
      { step: 7, description: 'Let rest for 10 minutes before carving. Serve with roasted potatoes.' },
    ],
  },

  // ========== HARD RECIPES (45-60+ min) ==========
  {
    title: 'Authentic Beef Lasagna',
    description: 'Layers of pasta, rich meat sauce, creamy béchamel, and melted cheese - Italian comfort food at its finest.',
    cuisine: 'Italian',
    difficulty: 'hard',
    prepTime: 30,
    cookingTime: 60,
    servings: 8,
    imageUrl: 'https://images.unsplash.com/photo-1574894709920-11b28e7367e3?w=800',
    ingredients: [
      { name: 'lasagna noodles', amount: 400, unit: 'g' },
      { name: 'ground beef', amount: 600, unit: 'g' },
      { name: 'Italian sausage', amount: 300, unit: 'g' },
      { name: 'onion', amount: 1, unit: 'piece' },
      { name: 'garlic', amount: 6, unit: 'cloves' },
      { name: 'crushed tomatoes', amount: 800, unit: 'g' },
      { name: 'tomato paste', amount: 6, unit: 'tbsp' },
      { name: 'ricotta cheese', amount: 450, unit: 'g' },
      { name: 'mozzarella', amount: 400, unit: 'g' },
      { name: 'parmesan cheese', amount: 150, unit: 'g' },
      { name: 'egg', amount: 2, unit: 'pieces' },
      { name: 'butter', amount: 60, unit: 'g' },
      { name: 'flour', amount: 60, unit: 'g' },
      { name: 'milk', amount: 500, unit: 'ml' },
      { name: 'basil', amount: 20, unit: 'g' },
    ],
    instructions: [
      { step: 1, description: 'Make meat sauce: Brown beef and sausage with onions and garlic. Add tomatoes, tomato paste, and basil. Simmer for 45 minutes.' },
      { step: 2, description: 'Make béchamel: Melt butter, whisk in flour, gradually add milk. Cook until thick.' },
      { step: 3, description: 'Mix ricotta with eggs, half the parmesan, salt, and pepper.' },
      { step: 4, description: 'Cook lasagna noodles according to package directions.' },
      { step: 5, description: 'Preheat oven to 180°C (350°F).' },
      { step: 6, description: 'Layer: meat sauce, noodles, ricotta mixture, mozzarella. Repeat 3 times. Top with béchamel and remaining cheeses.' },
      { step: 7, description: 'Cover with foil, bake for 40 minutes. Uncover, bake 15 more minutes until golden. Rest 15 minutes before serving.' },
    ],
  },
  {
    title: 'Coq au Vin',
    description: 'Classic French braised chicken in red wine with mushrooms, bacon, and pearl onions.',
    cuisine: 'French',
    difficulty: 'hard',
    prepTime: 25,
    cookingTime: 75,
    servings: 6,
    imageUrl: 'https://images.unsplash.com/photo-1633537731071-1e3bb7ed035d?w=800',
    ingredients: [
      { name: 'chicken thigh', amount: 1200, unit: 'g' },
      { name: 'bacon', amount: 200, unit: 'g' },
      { name: 'pearl onions', amount: 300, unit: 'g' },
      { name: 'mushrooms', amount: 400, unit: 'g' },
      { name: 'carrot', amount: 2, unit: 'pieces' },
      { name: 'garlic', amount: 4, unit: 'cloves' },
      { name: 'red wine', amount: 750, unit: 'ml' },
      { name: 'chicken stock', amount: 500, unit: 'ml' },
      { name: 'tomato paste', amount: 2, unit: 'tbsp' },
      { name: 'flour', amount: 3, unit: 'tbsp' },
      { name: 'butter', amount: 40, unit: 'g' },
      { name: 'thyme', amount: 4, unit: 'sprigs' },
      { name: 'bay leaf', amount: 2, unit: 'pieces' },
    ],
    instructions: [
      { step: 1, description: 'Cut bacon into lardons, cook until crispy. Remove and set aside.' },
      { step: 2, description: 'Season chicken with salt and pepper, brown in bacon fat. Remove and set aside.' },
      { step: 3, description: 'Add pearl onions and carrots to pot, cook for 5 minutes. Add mushrooms, cook 3 more minutes.' },
      { step: 4, description: 'Sprinkle flour over vegetables, stir for 1 minute.' },
      { step: 5, description: 'Add wine, stock, tomato paste, thyme, and bay leaves. Bring to boil.' },
      { step: 6, description: 'Return chicken and bacon to pot. Cover, simmer for 45 minutes until chicken is tender.' },
      { step: 7, description: 'Remove chicken. Reduce sauce for 10 minutes. Finish with butter, return chicken to pot. Serve with crusty bread.' },
    ],
  },
  {
    title: 'Homemade Ramen Bowl',
    description: 'Rich tonkotsu-style broth with tender pork belly, soft-boiled eggs, and fresh noodles.',
    cuisine: 'Japanese',
    difficulty: 'hard',
    prepTime: 30,
    cookingTime: 90,
    servings: 4,
    imageUrl: 'https://images.unsplash.com/photo-1557872943-16a5ac26437e?w=800',
    ingredients: [
      { name: 'pork belly', amount: 600, unit: 'g' },
      { name: 'ramen noodles', amount: 400, unit: 'g' },
      { name: 'egg', amount: 4, unit: 'pieces' },
      { name: 'chicken stock', amount: 2000, unit: 'ml' },
      { name: 'ginger', amount: 3, unit: 'tbsp' },
      { name: 'garlic', amount: 6, unit: 'cloves' },
      { name: 'soy sauce', amount: 80, unit: 'ml' },
      { name: 'miso paste', amount: 3, unit: 'tbsp' },
      { name: 'scallion', amount: 6, unit: 'pieces' },
      { name: 'nori', amount: 4, unit: 'sheets' },
      { name: 'bamboo shoots', amount: 200, unit: 'g' },
      { name: 'sesame oil', amount: 2, unit: 'tbsp' },
    ],
    instructions: [
      { step: 1, description: 'Make broth: Simmer chicken stock with ginger, garlic, and half the soy sauce for 1 hour.' },
      { step: 2, description: 'Braise pork belly: Season with salt, sear all sides, then braise in remaining soy sauce and water for 90 minutes until tender.' },
      { step: 3, description: 'Make soft-boiled eggs: Boil for exactly 6.5 minutes, ice bath, peel, and marinate in soy sauce.' },
      { step: 4, description: 'Strain broth, whisk in miso paste and sesame oil.' },
      { step: 5, description: 'Slice pork belly, chop scallions, and prepare bamboo shoots.' },
      { step: 6, description: 'Cook ramen noodles according to package directions.' },
      { step: 7, description: 'Assemble bowls: noodles, hot broth, pork belly, halved eggs, scallions, bamboo shoots, and nori. Serve immediately.' },
    ],
  },
  {
    title: 'Moroccan Lamb Tagine',
    description: 'Aromatic slow-cooked lamb with apricots, almonds, and warming spices in a traditional clay pot.',
    cuisine: 'Moroccan',
    difficulty: 'hard',
    prepTime: 25,
    cookingTime: 120,
    servings: 6,
    imageUrl: 'https://images.unsplash.com/photo-1639024471283-03518883512d?w=800',
    ingredients: [
      { name: 'lamb shoulder', amount: 1200, unit: 'g' },
      { name: 'onion', amount: 2, unit: 'pieces' },
      { name: 'garlic', amount: 5, unit: 'cloves' },
      { name: 'dried apricots', amount: 200, unit: 'g' },
      { name: 'chickpeas', amount: 400, unit: 'g' },
      { name: 'tomato', amount: 3, unit: 'pieces' },
      { name: 'almonds', amount: 100, unit: 'g' },
      { name: 'ginger', amount: 2, unit: 'tbsp' },
      { name: 'cumin', amount: 2, unit: 'tsp' },
      { name: 'cinnamon', amount: 1, unit: 'tsp' },
      { name: 'coriander', amount: 2, unit: 'tsp' },
      { name: 'saffron', amount: 0.5, unit: 'tsp' },
      { name: 'honey', amount: 2, unit: 'tbsp' },
      { name: 'cilantro', amount: 30, unit: 'g' },
    ],
    instructions: [
      { step: 1, description: 'Cut lamb into large chunks, season with salt, pepper, cumin, cinnamon, coriander, and saffron.' },
      { step: 2, description: 'Brown lamb in batches in a tagine or heavy pot. Remove and set aside.' },
      { step: 3, description: 'Cook onions until soft, add garlic and ginger, cook for 2 minutes.' },
      { step: 4, description: 'Return lamb to pot, add diced tomatoes, chickpeas, and enough water to cover.' },
      { step: 5, description: 'Bring to boil, reduce to simmer, cover and cook for 1.5 hours.' },
      { step: 6, description: 'Add dried apricots and honey, cook for 30 more minutes until lamb is fall-apart tender.' },
      { step: 7, description: 'Toast almonds in a dry pan. Serve tagine garnished with almonds and fresh cilantro over couscous.' },
    ],
  },

  // ========== VEGETARIAN OPTIONS ==========
  {
    title: 'Vegetarian Buddha Bowl',
    description: 'Nourishing bowl packed with quinoa, roasted vegetables, avocado, and tahini dressing.',
    cuisine: 'American',
    difficulty: 'easy',
    prepTime: 15,
    cookingTime: 25,
    servings: 4,
    imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800',
    ingredients: [
      { name: 'quinoa', amount: 200, unit: 'g' },
      { name: 'sweet potato', amount: 400, unit: 'g' },
      { name: 'chickpeas', amount: 400, unit: 'g' },
      { name: 'kale', amount: 200, unit: 'g' },
      { name: 'avocado', amount: 2, unit: 'pieces' },
      { name: 'tahini', amount: 80, unit: 'ml' },
      { name: 'lemon', amount: 2, unit: 'pieces' },
      { name: 'garlic', amount: 2, unit: 'cloves' },
      { name: 'olive oil', amount: 4, unit: 'tbsp' },
      { name: 'cumin', amount: 1, unit: 'tsp' },
    ],
    instructions: [
      { step: 1, description: 'Cook quinoa according to package directions.' },
      { step: 2, description: 'Cube sweet potato, toss with oil, cumin, salt. Roast at 200°C for 20 minutes.' },
      { step: 3, description: 'Drain chickpeas, toss with oil and spices. Roast alongside sweet potatoes.' },
      { step: 4, description: 'Massage kale with a bit of lemon juice and oil to soften.' },
      { step: 5, description: 'Make dressing: blend tahini, lemon juice, garlic, and water until smooth.' },
      { step: 6, description: 'Assemble bowls with quinoa, roasted vegetables, chickpeas, kale, and sliced avocado.' },
      { step: 7, description: 'Drizzle with tahini dressing and serve.' },
    ],
  },
  {
    title: 'Mushroom Risotto',
    description: 'Creamy Italian rice dish with earthy mushrooms, parmesan, and white wine.',
    cuisine: 'Italian',
    difficulty: 'medium',
    prepTime: 10,
    cookingTime: 35,
    servings: 4,
    imageUrl: 'https://images.unsplash.com/photo-1476124369491-a5bf07b8ee7b?w=800',
    ingredients: [
      { name: 'arborio rice', amount: 300, unit: 'g' },
      { name: 'mushrooms', amount: 400, unit: 'g' },
      { name: 'onion', amount: 1, unit: 'piece' },
      { name: 'garlic', amount: 3, unit: 'cloves' },
      { name: 'white wine', amount: 150, unit: 'ml' },
      { name: 'vegetable stock', amount: 1200, unit: 'ml' },
      { name: 'parmesan cheese', amount: 100, unit: 'g' },
      { name: 'butter', amount: 60, unit: 'g' },
      { name: 'olive oil', amount: 2, unit: 'tbsp' },
      { name: 'thyme', amount: 4, unit: 'sprigs' },
      { name: 'parsley', amount: 20, unit: 'g' },
    ],
    instructions: [
      { step: 1, description: 'Keep stock warm in a separate pot.' },
      { step: 2, description: 'Slice mushrooms. Heat half the butter and oil, cook mushrooms until golden. Set aside.' },
      { step: 3, description: 'In same pot, cook diced onion until soft. Add garlic and rice, toast for 2 minutes.' },
      { step: 4, description: 'Add wine, stir until absorbed.' },
      { step: 5, description: 'Add stock one ladle at a time, stirring constantly. Wait until liquid is absorbed before adding more.' },
      { step: 6, description: 'After 18-20 minutes, rice should be creamy and al dente. Stir in mushrooms, remaining butter, and parmesan.' },
      { step: 7, description: 'Garnish with fresh parsley and extra parmesan. Serve immediately.' },
    ],
  },

  // ========== BREAKFAST OPTIONS ==========
  {
    title: 'Fluffy Pancakes',
    description: 'Classic American breakfast pancakes - light, fluffy, and perfect with maple syrup.',
    cuisine: 'American',
    difficulty: 'easy',
    prepTime: 10,
    cookingTime: 15,
    servings: 4,
    imageUrl: 'https://images.unsplash.com/photo-1528207776546-365bb710ee93?w=800',
    ingredients: [
      { name: 'flour', amount: 250, unit: 'g' },
      { name: 'milk', amount: 300, unit: 'ml' },
      { name: 'egg', amount: 2, unit: 'pieces' },
      { name: 'butter', amount: 50, unit: 'g' },
      { name: 'sugar', amount: 30, unit: 'g' },
      { name: 'baking powder', amount: 2, unit: 'tsp' },
      { name: 'vanilla extract', amount: 1, unit: 'tsp' },
      { name: 'salt', amount: 0.5, unit: 'tsp' },
    ],
    instructions: [
      { step: 1, description: 'Mix flour, sugar, baking powder, and salt in a large bowl.' },
      { step: 2, description: 'In another bowl, whisk together milk, eggs, melted butter, and vanilla.' },
      { step: 3, description: 'Pour wet ingredients into dry, mix gently until just combined (lumps are okay).' },
      { step: 4, description: 'Heat a griddle or pan over medium heat, lightly butter.' },
      { step: 5, description: 'Pour 1/4 cup batter per pancake. Cook until bubbles form on surface, about 2-3 minutes.' },
      { step: 6, description: 'Flip and cook another 2 minutes until golden.' },
      { step: 7, description: 'Serve hot with butter and maple syrup.' },
    ],
  },
  {
    title: 'Spanish Tortilla',
    description: 'Classic potato and egg omelette - perfect for breakfast, lunch, or tapas.',
    cuisine: 'Spanish',
    difficulty: 'medium',
    prepTime: 15,
    cookingTime: 30,
    servings: 6,
    imageUrl: 'https://images.unsplash.com/photo-1568822617270-2e6141984c1d?w=800',
    ingredients: [
      { name: 'potato', amount: 600, unit: 'g' },
      { name: 'egg', amount: 6, unit: 'pieces' },
      { name: 'onion', amount: 1, unit: 'piece' },
      { name: 'olive oil', amount: 150, unit: 'ml' },
      { name: 'salt', amount: 1, unit: 'tsp' },
    ],
    instructions: [
      { step: 1, description: 'Peel and thinly slice potatoes. Slice onion thinly.' },
      { step: 2, description: 'Heat olive oil in a large pan over medium heat. Add potatoes and onions.' },
      { step: 3, description: 'Cook gently for 20 minutes, stirring occasionally, until potatoes are tender but not browned.' },
      { step: 4, description: 'Drain potatoes (save oil for another use). Let cool slightly.' },
      { step: 5, description: 'Beat eggs with salt. Mix in potato-onion mixture.' },
      { step: 6, description: 'Heat 2 tbsp oil in the same pan. Pour in egg mixture, cook for 5-7 minutes until edges set.' },
      { step: 7, description: 'Place a plate over pan, flip tortilla onto plate, slide back into pan. Cook 3-5 more minutes. Serve warm or room temperature.' },
    ],
  },

  // ========== DESSERTS ==========
  {
    title: 'Chocolate Lava Cake',
    description: 'Decadent individual chocolate cakes with a molten center - dessert perfection.',
    cuisine: 'French',
    difficulty: 'medium',
    prepTime: 15,
    cookingTime: 12,
    servings: 4,
    imageUrl: 'https://images.unsplash.com/photo-1624353365286-3f8d62daad51?w=800',
    ingredients: [
      { name: 'dark chocolate', amount: 200, unit: 'g' },
      { name: 'butter', amount: 100, unit: 'g' },
      { name: 'egg', amount: 2, unit: 'pieces' },
      { name: 'egg yolk', amount: 2, unit: 'pieces' },
      { name: 'sugar', amount: 60, unit: 'g' },
      { name: 'flour', amount: 40, unit: 'g' },
      { name: 'vanilla extract', amount: 1, unit: 'tsp' },
    ],
    instructions: [
      { step: 1, description: 'Preheat oven to 220°C (425°F). Butter and flour 4 ramekins.' },
      { step: 2, description: 'Melt chocolate and butter together in a double boiler.' },
      { step: 3, description: 'In a bowl, whisk eggs, egg yolks, sugar, and vanilla until thick and pale.' },
      { step: 4, description: 'Fold melted chocolate into egg mixture.' },
      { step: 5, description: 'Gently fold in flour until just combined.' },
      { step: 6, description: 'Divide batter among ramekins.' },
      { step: 7, description: 'Bake for 12 minutes - edges should be set but center still soft. Let stand 1 minute, invert onto plates. Serve immediately with ice cream.' },
    ],
  },
  {
    title: 'Classic Tiramisu',
    description: 'Layers of espresso-soaked ladyfingers and mascarpone cream - Italian elegance in every bite.',
    cuisine: 'Italian',
    difficulty: 'medium',
    prepTime: 30,
    cookingTime: 0,
    servings: 8,
    imageUrl: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=800',
    ingredients: [
      { name: 'ladyfingers', amount: 300, unit: 'g' },
      { name: 'mascarpone', amount: 500, unit: 'g' },
      { name: 'egg yolk', amount: 4, unit: 'pieces' },
      { name: 'sugar', amount: 100, unit: 'g' },
      { name: 'espresso', amount: 300, unit: 'ml' },
      { name: 'coffee liqueur', amount: 60, unit: 'ml' },
      { name: 'cocoa powder', amount: 30, unit: 'g' },
      { name: 'vanilla extract', amount: 1, unit: 'tsp' },
    ],
    instructions: [
      { step: 1, description: 'Make espresso, mix with coffee liqueur. Let cool completely.' },
      { step: 2, description: 'Whisk egg yolks and sugar over double boiler until thick and pale, about 5 minutes.' },
      { step: 3, description: 'Remove from heat, cool slightly. Fold in mascarpone and vanilla until smooth.' },
      { step: 4, description: 'Quickly dip ladyfingers in espresso (don\'t soak), arrange in a single layer in dish.' },
      { step: 5, description: 'Spread half the mascarpone cream over ladyfingers.' },
      { step: 6, description: 'Repeat with another layer of dipped ladyfingers and remaining cream.' },
      { step: 7, description: 'Cover and refrigerate at least 4 hours or overnight. Dust with cocoa powder before serving.' },
    ],
  },

  // ========== QUICK & HEALTHY ==========
  {
    title: 'Greek Salad',
    description: 'Fresh Mediterranean salad with tomatoes, cucumbers, olives, and feta cheese.',
    cuisine: 'Greek',
    difficulty: 'easy',
    prepTime: 15,
    cookingTime: 0,
    servings: 4,
    imageUrl: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=800',
    ingredients: [
      { name: 'tomato', amount: 4, unit: 'pieces' },
      { name: 'cucumber', amount: 2, unit: 'pieces' },
      { name: 'red onion', amount: 1, unit: 'piece' },
      { name: 'bell pepper', amount: 1, unit: 'piece' },
      { name: 'feta cheese', amount: 200, unit: 'g' },
      { name: 'kalamata olives', amount: 150, unit: 'g' },
      { name: 'olive oil', amount: 80, unit: 'ml' },
      { name: 'red wine vinegar', amount: 30, unit: 'ml' },
      { name: 'oregano', amount: 1, unit: 'tsp' },
    ],
    instructions: [
      { step: 1, description: 'Cut tomatoes into wedges, cucumber into thick half-moons.' },
      { step: 2, description: 'Slice red onion thinly, cut bell pepper into strips.' },
      { step: 3, description: 'Combine vegetables in a large bowl with olives.' },
      { step: 4, description: 'Whisk together olive oil, vinegar, oregano, salt, and pepper.' },
      { step: 5, description: 'Pour dressing over salad, toss gently.' },
      { step: 6, description: 'Top with crumbled feta cheese. Serve immediately.' },
    ],
  },
  {
    title: 'Grilled Salmon with Asparagus',
    description: 'Heart-healthy salmon fillet with roasted asparagus and lemon butter sauce.',
    cuisine: 'American',
    difficulty: 'easy',
    prepTime: 10,
    cookingTime: 20,
    servings: 4,
    imageUrl: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=800',
    ingredients: [
      { name: 'salmon fillet', amount: 600, unit: 'g' },
      { name: 'asparagus', amount: 500, unit: 'g' },
      { name: 'lemon', amount: 2, unit: 'pieces' },
      { name: 'garlic', amount: 3, unit: 'cloves' },
      { name: 'butter', amount: 40, unit: 'g' },
      { name: 'olive oil', amount: 3, unit: 'tbsp' },
      { name: 'dill', amount: 15, unit: 'g' },
      { name: 'salt', amount: 1, unit: 'tsp' },
      { name: 'black pepper', amount: 0.5, unit: 'tsp' },
    ],
    instructions: [
      { step: 1, description: 'Preheat oven to 200°C (400°F).' },
      { step: 2, description: 'Trim asparagus ends, toss with olive oil, salt, and pepper. Spread on baking sheet.' },
      { step: 3, description: 'Season salmon with salt, pepper, and minced garlic. Place on same sheet.' },
      { step: 4, description: 'Roast for 12-15 minutes until salmon flakes easily and asparagus is tender.' },
      { step: 5, description: 'Meanwhile, melt butter with lemon juice and chopped dill.' },
      { step: 6, description: 'Serve salmon and asparagus drizzled with lemon butter sauce.' },
    ],
  },
];
